name: blo_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  geolocator: ^11.0.0
  http: ^1.2.1
  sqflite: ^2.3.2
  path: ^1.9.0
  image_picker: ^1.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # ✅ Background service & job scheduler
  flutter_background_service: ^5.0.5
  workmanager: ^0.8.0

  # ✅ Optional (useful for permission status display & settings redirection)
  permission_handler: ^11.3.1
  location: ^8.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
